# Generated by Django 3.2.8 on 2021-11-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='encrypt_pswds',
            field=models.BooleanField(default=True),
        ),
    ]
