# Generated by Django 3.2.8 on 2021-10-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Email should be verified.'),
        ),
    ]
