# Generated by Django 3.2.8 on 2021-11-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='pswd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
