# Generated by Django 3.2.8 on 2021-10-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_credentials_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
