# Generated by Django 3.2.8 on 2021-10-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_alter_credentials_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='encrypt_pswd',
        ),
    ]
